### ISSUE TITLE
Black screen when starting VHBB

### ISSUE THREAD

**Issue by nex86** [devnoname120/vhbb#106]
two spash screens appear and then I'm getting a black screen when launching VHBB 0.92.
using 3.65 ENSO.
log:

[VHBB_2021-06-05_22-06-55.log](https://github.com/devnoname120/vhbb/files/6603177/VHBB_2021-06-05_22-06-55.log)

**Comment by chicagotaco** [comment]
Having this issue as well on ENSO 3.60 (PSTV)

**Comment by chicagotaco** [comment]
Managed to fix it by restarting the app and just waiting a minute.

**Comment by nex86** [comment]
> Managed to fix it by restarting the app and just waiting a minute.

Restarting and waiting doesn’t fix the issue for me

**Comment by Sergeybond97** [comment]
> Managed to fix it by restarting the app and just waiting a minute.

That helped me too
(I have 3.60 firmware)

**Comment by robsdedude** [comment]
If your internet is slow, you might have to wait several minutes. The app is downloading the icons of all available homebrew. If it didn't crash, wait longer. If it's still black after 15 minutes, something is probably wrong—potentially with your network. A progessbar surely would be helpful but is another topic.

Checking the logs confirms my suspicion: VHBB was still downloading icons.
