### ISSUE TITLE
First time load crash on newest version

### ISSUE THREAD

**Issue by doctadee** [devnoname120/vhbb#107]
**Describe the bug**

After installing the newest vpk and opening the app for the first time the screen is black and then opens a webbrowser  to the address http://detectportal.firefox.com/success.txt

the page itself cannot be displayed with error code (C2-14921-7)

**To Reproduce**

1. Install vpk
2. click on HBB bubble for first time

**Expected behavior**
Both splash screens display and then a black screen. After black screen the home brew browser is open

**Log file**
[VHBB_2021-06-22_18-02-16.log](https://github.com/devnoname120/vhbb/files/6697645/VHBB_2021-06-22_18-02-16.log)
-->

**Comment by devnoname120** [comment]
@doctadee Looks like your network is not working if the browser cannot open that page.

**Comment by doctadee** [comment]
@devnoname120  thank you for the prompt response. I will look into my dns settings/network settings.
