### ISSUE TITLE
Help me install granny and...

### ISSUE THREAD

**Issue by Jatomy** [devnoname120/vhbb#111]
I installed granny and I had only 400mb free, then it went to 75 of the download and it was canceled for not having the full space, and now I only have 0mb free and I want to know where the granny files are saved to delete them and have my space again (it has also happened to me with more games such as the retroarch emulator and the flycast emulator, please I want to recover all that space that I have lost

**Comment by robsdedude** [comment]
See if any of these files/folders exist. You should be able to delete them safely. `ux0:/temp/pkg/...`, `ux0:/temp/data.zip`, and `ux0:/temp/download.vpk`.

**Comment by Jatomy** [comment]
There my god is giving me something from 27mb free step to 626 thank you very much
