### ISSUE TITLE
VHBB C2-12828-1 Error

### ISSUE THREAD

**Issue by DraxDauragon** [devnoname120/vhbb#114]
VHBB Crashing on boot

I've Rebuilt the Database, Unsafe Homebrew in settings is checked in Henkaku Settings, and deleted the Tai and VHBB folders with no luck. Idk if its useful info or not but when there is a VHBB folder it crashes pre Gekihen screen and without a VHBB folder it crashes post Gekihen screeb. Ty for any help.

**Comment by rlymxrtel** [comment]
me too im having the same issue, whenever i open VHBB i get past the first screen but then when it gets to the white "gekihen homebrew contest" it gives me the error message the (CS-12828-1), ive also tried uninstalling the vhbb folder the tai folder and rebuilding database but it still doesn't work for me. have you found any solutions to fix it?

**Comment by u3shit** [comment]
The problem is with vitadb, the api enpoint used by vhbb is broken and returns a bunch of PHP warnings: https://rinnegatamante.it/vitadb/list_hbs_yaml.php (the json endpoint seem to work though)
Ping @Rinnegatamante

**Comment by Rinnegatamante** [comment]
Should be working now.

**Comment by DraxDauragon** [comment]
Ty so much, was losing my mind for a few hours trying to figure out what was wrong.

**Comment by rlymxrtel** [comment]
it opened up for me too, but when I try and click on something to download it it gives me the same error messge

**Comment by rlymxrtel** [comment]
i tried download daedelus and it gave me the same error message
