### ISSUE TITLE
Can't browse Pickr VITA / Numpty Physics

### ISSUE THREAD

**Issue by devnoname120** [devnoname120/vhbb#12]
The screenshot is downloaded correctly, but the loading fails.
Maybe because the filename is too long: http://vitadb.rinnegatamante.it/screenshots/a048dfcae7548219d5f0f50217f78b156dfe20786d798c2b7a1de72659875fb8.png

#10 would prevent the crash, but not fix this issue.

**Comment by devnoname120** [comment]
The crash is caused by incorrect extension for some screenshots (here `.png` when it should be `.jpg`).

**Comment by Agrecan** [comment]
Hi, thanks for the application. Are you going to get an update? The current version worked well for me, but since today it does not work for me, it says error C2-12828-1. Yesterday it worked perfect but not today. Greetings.

**Comment by devnoname120** [comment]
I haven't had the time to work on this issue. https://github.com/devnoname120/vhbb/issues/28
