### ISSUE TITLE
Minesweeper Error

### ISSUE THREAD

**Issue by metal-velcro** [devnoname120/vhbb#13]
Upon downloading and after extracting it will report error faking app signature. 

![2017-04-28-023233](https://cloud.githubusercontent.com/assets/20314349/25517989/d73004de-2bbf-11e7-90b8-04104a684c83.jpg)

**Comment by ArkSource** [comment]
Looks like it's a corrupt vpk on VitaDB.
Installing via VitaShell fails to create head.bin as well.

**Comment by devnoname120** [comment]
@metal-velcro It seems to be a vitadb issue rather than vhbb, please post the issue here: https://github.com/Rinnegatamante/VitaDB
