### ISSUE TITLE
Problem in install app

### ISSUE THREAD

**Issue by BenMitnicK** [devnoname120/vhbb#14]
Install always failed with everything 
" Error faking app signature "

**Comment by devnoname120** [comment]
Which homebrews did you try?

**Comment by BenMitnicK** [comment]
Anything it's always the same error

**Comment by ArkSource** [comment]
@BenMitnicK 
The only HB i can replicate this error with so far is 'Minesweeper', which has already been logged and will be attended to shortly.
Are you sure you have enough memory available on `ux0:`?

**Comment by BenMitnicK** [comment]
I have 2go free. I wanted the game 4rows it did not work but my test was random I can not tell you which game but 4rows Minesweeper SpiderVita error message but I just test this morning like random vitapong and VitaHairHockey installation ok

**Comment by ArkSource** [comment]
I have tested the games you mentioned and can confirm that their vpk files are indeed corrupt. We will let Rinnegatamante know of this as some of these games were working fine a few weeks ago. Shouldn't be too long for fresh files to be uploaded to the DB.

I'll also scan through all other games in the DB for any other problematic vpk's.
Thanks @BenMitnicK

**Comment by Rinnegatamante** [comment]
All three homebrews got fixed. It was related to a wrong titleid in param.sfo.

**Comment by ArkSource** [comment]
Thanks mate

**Comment by BenMitnicK** [comment]
Your welcome @ArkSource :) and thx @Rinnegatamante :)
