### ISSUE TITLE
Latestest Entries Crash Upon Download

### ISSUE THREAD

**Issue by metal-velcro** [devnoname120/vhbb#18]
Latestr apps added cause 
(C2-12828-1) 

Error upon install, here is the apps effected. Tested on OLED Vita with Enso 9&10 as well as PSTV F1 Enso v9&10

Adrenaline Easy Installer, PSPHBB, Eucliod, Autoboot Config, AppManager Plus, Mediaimporter, Vita Moonlight & Flyer Death Match. Cardunlock and below instasll just fine. 
![2017-05-27-120935](https://cloud.githubusercontent.com/assets/20314349/26522782/3ec84124-42d6-11e7-899b-01f7af557041.jpg)

**Comment by devnoname120** [comment]
You need to update to 0.81.

**Comment by metal-velcro** [comment]
I am on 0.81 and this error only occurs on my systems I have Enso enabled on.

**Comment by devnoname120** [comment]
Your screenshot looks like an old version since categories don't appear.
Could you try to uninstall the app, download it [from here](https://github.com/devnoname120/vhbb/releases/download/0.81/VitaHBBrowser.vpk), and install it again? Thanks.

VHBB not working on PSTV is a known issue.
