### ISSUE TITLE
Doesnt support the vita's "Fast Scroll" feature.

### ISSUE THREAD

**Issue by SilicaAndPina** [devnoname120/vhbb#21]
i tried to do the vita's fast scroll feature inside VhBB (the thing where you do the scroll gesture and hold it right at the end and it just keeps scrolling..) doesnt work on vhbb

**Comment by devnoname120** [comment]
Interesting, I didn't know that this feature existed.
I can't promise I will add it though.

**Comment by devnoname120** [comment]
I decided not to implement it.
