### ISSUE TITLE
vhbb should not crash when displaying a corrupted icon

### ISSUE THREAD

**Issue by shadowwolf86** [devnoname120/vhbb#23]
Hi i keep crashing on utilities button and when i scroll all the way down on the new button. Doesn't happen on the the other buttons. It gives me a c2-12828-1 error and says saved core file succeeded
![20170724_140430](https://user-images.githubusercontent.com/30416727/28537539-405f0a7e-7079-11e7-9a89-b6e7831cea84.jpg)

**Comment by devnoname120** [comment]
I can't reproduce it.

Can you download the [latest version](https://github.com/devnoname120/vhbb/releases/tag/0.81) and take a video?

**Comment by shadowwolf86** [comment]
here you go https://youtu.be/GceN1sTk16E
https://www.youtube.com/watch?v=BgDKGFP43wM
i installed the version you just sent me. It doesn't happen on the other tabs though like games ports or emulators.

**Comment by devnoname120** [comment]
Hm, I'm not sure what happens. Could you provide me with the coredump file that is specified in the error dialog?

**Comment by shadowwolf86** [comment]
here http://www.mediafire.com/file/cwcwrfl1i8wj8y3/psp2core-1501538349-0x0000bd2199-eboot.bin.psp2dmp

**Comment by devnoname120** [comment]
I suspect this happens because of a corrupted icon.
Could you delete the folder `ux0:data/VitaHbBrowser/` and let me know if this fixes your issue?

```
=== THREADS ===
    VHBB00001
        ID: 0x40010003
        Stop reason: 0x30004 (Data abort exception)
        Status: 0x1 (Running)
        PC: 0xe00830c8 (SceGxm@1 + 0x1abf8)
    SceCommonDialogWorker
        ID: 0x40010073
        Stop reason: 0x0 (No reason)
        Status: 0x8 (Waiting)
        PC: 0xe00087f4 (SceLibKernel@1 + 0x6304)
    SceGxmDisplayQueue
        ID: 0x400100af
        Stop reason: 0x0 (No reason)
        Status: 0x8 (Waiting)
        PC: 0xe0008c04 (SceLibKernel@1 + 0x6714)
    nosleep_thread
        ID: 0x400100d3
        Stop reason: 0x0 (No reason)
        Status: 0x8 (Waiting)
        PC: 0x81173b68 (/VitaHBBrowser.elf@1 + 0x161b68)

=== THREAD "VHBB00001" <0x40010003> CRASHED (Data abort exception) ===

DISASSEMBLY AROUND LR: 0x81021af6 (Thumb):

0000fae6 <_ZN7Texture10DrawResizeERK5PointS2_+0x2>:
}


// vita2d doesn't have a draw resize function: https://github.com/xerpi/libvita2d/issues/42
int Texture::DrawResize(const Point &pt1, const Point &dimensions)
{
    fae6:	4604      	mov	r4, r0
    fae8:	ed2d 8b02 	vpush	{d8}
    faec:	460e      	mov	r6, r1
    faee:	4615      	mov	r5, r2
	// Careful, vita2d_texture_get_width() will crash if vita2d_start_drawing() was not called
	float width = vita2d_texture_get_width(texture.get());
    faf0:	6800      	ldr	r0, [r0, #0]
    faf2:	f035 f905 	bl	44d00 <vita2d_texture_get_width>
!!! 		ee07 0a90 	vmov	s15, r0 !!!
    fafa:	eeb8 8a67 	vcvt.f32.u32	s16, s15
	float height = vita2d_texture_get_height(texture.get());
    fafe:	6820      	ldr	r0, [r4, #0]
    fb00:	f035 f900 	bl	44d04 <vita2d_texture_get_height>
    fb04:	Address 0x000000000000fb04 is out of bounds.

```

**Comment by shadowwolf86** [comment]
hey it worked! I deleted the folder. It took a while to boot up but it doesn't crash anymore.

**Comment by shadowwolf86** [comment]
thanks for helping me out.

**Comment by devnoname120** [comment]
You're welcome. I'll keep this issue open to remind myself to harden image loading error handling, so that it fails gracefully instead of crashing.

**Comment by SnakeDeath** [comment]
it keeps crashing for me too and removing ux0:data/VitaHbBrowser doesnt help , any ideas?

**Comment by devnoname120** [comment]
VHBB is broken for a few days, I haven't investigated yet. See https://github.com/devnoname120/vhbb/issues/28

**Comment by SnakeDeath** [comment]
i see , hope it get fixed soon 
GL
