### ISSUE TITLE
Crashes on startup if Proxy is used

### ISSUE THREAD

**Issue by anden11** [devnoname120/vhbb#24]
I like to use the VitaUpdateBlocker for my 3.60 PSTV and it does a good job most of the time, but when I try to launch this program it crashes on the GEKIHEN Contest loading screen with error C2-12828-1 until I change my Vita's network settings to not use the proxy.

**Comment by devnoname120** [comment]
Can you access this link from your Vita browser when the proxy settings are used?
`https://rinnegatamante.it/vitadb/list_hbs_yaml.php`

**Comment by anden11** [comment]
Yes, I can: http://i.imgur.com/lTFtuba.jpg

Although, I do get a question if I want to accept the invalid HTTPS certificate first, but any HTTPS does that when I have proxy enabled. I guess it's a side effect of the redirection the proxy does.

**Comment by devnoname120** [comment]
Alright, I'll try to fix it when I get the chance to.

**Comment by devnoname120** [comment]
VHBB uses the system's proxy settings.
Could you try to enable this proxy in your PC browser and see if you can access this link? `https://rinnegatamante.it/vitadb/list_hbs_yaml.php`

**Comment by anden11** [comment]
Sorry, but the program hangs on a black screen after the GEKIHEN Contest loading screen.

**Comment by anden11** [comment]
I looked into setting up such an environment, and it's not something I'll be able to do unfortunately. Any other way I can help?

**Comment by ZafotheNinja** [comment]
Core dump: https://drive.google.com/file/d/1k6unwt5DGWDVMjOxv5nqfvCouYcnHB0H/view?usp=drivesdk

**Comment by devnoname120** [comment]
Can you provide me with the log as well?

**Comment by ZafotheNinja** [comment]
Where is the log located?

**Comment by devnoname120** [comment]
See here for instructions: https://github.com/devnoname120/vhbb/releases/tag/0.83

**Comment by ZafotheNinja** [comment]
Okay, I'll take a look when I get home.

**Comment by anden11** [comment]
[VHBB_2019-02-27_20-05-54.log](https://github.com/devnoname120/vhbb/files/2911968/VHBB_2019-02-27_20-05-54.log)
[VHBB_2019-02-27_20-24-42.log](https://github.com/devnoname120/vhbb/files/2911969/VHBB_2019-02-27_20-24-42.log)

Alright, I actually managed to set up the SDK and compiled my own build with network debugging enabled, which doesn't seem to work anyway (nothing appears in the listening nc when VHBB runs, and then VHBB crashes as usual). I used the file debugging instead, and included logs from both the official 0.83 and my own build. After reading those logs, my guess is VHBB ignores the proxy and tries to connect without it (which won't work in my case, and is why I'm using a proxy in the first place).

Other homebrews like PKGJ is able to use the proxy (even before it switched to background downloads), so it should be doable.

**Comment by devnoname120** [comment]
Alright thanks for your tests.

**Comment by devnoname120** [comment]
@anden11 @ZafotheNinja Could you try this version and let me know if using a proxy works properly now? https://dev.azure.com/devnoname120/d2401ccb-7e2b-4a16-bbe9-4f690333825a/_apis/build/builds/31/artifacts?artifactName=Vita+Package+(VPK)&fileId=18342F2364B529E9B1B1C4B1060C3E7C835F4F8C01DE4C0E352A661AA673BCE302&fileName=VitaHBBrowser.vpk&api-version=5.0-preview.3

**Comment by devnoname120** [comment]
I've used Charles proxy and I can confirm that this is indeed fixed. All the requests go through the configured proxy now.
