### ISSUE TITLE
Error C-12828-1 on startup

### ISSUE THREAD

**Issue by Linkmonster666** [devnoname120/vhbb#25]
I get this error every time I start the app. Tried reinstalling, rebuild database and formatting memory card. I can't seem to get the app to work. Tried both 0.81 and 0.80. Any help would be appreciated!!

**Comment by ArkSource** [comment]
@Linkmonster666
Make sure you have 'Enable Unsafe Homebrew' checked under HENkaku settings.
delete the VHBB folder (ux0:data/vhbb) and launch VHBB again.
Give it some time for first launch.

**Comment by Linkmonster666** [comment]
I do have unsafe enabled. Sorry forgot to mention that. lol I'm not sure what is going on. I deleted folder as you suggested still got error and crash. I'm using Vita Shell 1.62. Tried using Molecule shell as well. Same results. Thanks for reply!

**Comment by Linkmonster666** [comment]
I don't know if this matters but the psp2core lists the eboot.bin in the error dialog.

**Comment by Linkmonster666** [comment]
@ArkSource Also using Enzo, sorry trying to give as much info as I can. Also thanks for all the work you guys have done!

**Comment by ArkSource** [comment]
are you running any plugins under *all ?
you can also try refreshing your ux0:tai/config.txt then reboot your Vita.

Check out post 15 here-> https://github.com/devnoname120/vhbb/issues/15
do all 3 steps listed by CelesteBlue-dev, then **reboot.**
let me know how you go.
(could you also attach your psp2core here.)

**Comment by Linkmonster666** [comment]
[psp2core-1503279896-0x00000531b3-eboot.bin.psp2dmp.zip](https://github.com/devnoname120/vhbb/files/1237541/psp2core-1503279896-0x00000531b3-eboot.bin.psp2dmp.zip)
@ArkSource tried those, moved my tai folder to a back up folder and rebooted. Still getting error. Do you know if anyone has confirmed VHBB to work on Enso? I'm going to uninstall it and I'll let you know of results.

**Comment by Linkmonster666** [comment]
Hmmm took a lot longer to crash after uninstall of enso. Gonna keep trying will post if I fix it. Thanks!

**Comment by ArkSource** [comment]
no shouldn't be Enso, i haven't seen any issues so far.
C-12828-1 is a pain in my ass though :-)
I get it with VitaShell every so often.
Yet to pint-point the actual causes behind it. probably aliens or ghosts.

**Comment by Linkmonster666** [comment]
XD I'm going to blame Sony. I feel like they knew at some point the vita was gonna be a bigger Homebrew scene than the original psp so they put code in the vita to just fuck everyone up.

**Comment by Linkmonster666** [comment]
@ArkSource Just reinstalled enso and deleted the VHBB folder. Same result. lol Been trying to get it to work for like a week.

**Comment by Linkmonster666** [comment]
@ArkSource Seems to be a network error. I followed this guide (http://community.eu.playstation.com/t5/PS-Vita/Fixing-the-Error-c2-12828-1-issue-on-your-Vita/td-p/15328217) and got the error on the GekiHen splash screen rather than the VHBB splash screen.

**Comment by Linkmonster666** [comment]
@ArkSource So I had to do a system restore and format memory card due to some issues with adrenaline. After that I installed the browser and it's working. I dunno how but something fixed it. lol
