### ISSUE TITLE
Crash when trying to open "PC Link" homebrew page

### ISSUE THREAD

**Issue by EpicLPer** [devnoname120/vhbb#30]
As title says. Start up VHBB, go to the "New" page, click on "PC Link" and it'll crash.

**Comment by devnoname120** [comment]
VHBB is unable to load the screenshot, I'll need to investigate why.

**Comment by EpicLPer** [comment]
Why isn't it just not loading it tho? I think VHBB needs a bit of an error handling update ;)

**Comment by devnoname120** [comment]
I don't know, there is a kinda related issue: https://github.com/devnoname120/vhbb/issues/23

**Comment by devnoname120** [comment]
This will be fixed in the next release.
