### ISSUE TITLE
Won't go past splash screen

### ISSUE THREAD

**Issue by Felthry** [devnoname120/vhbb#38]
I've been sitting on the splash screen for a few minutes now, and I'm pretty sure it's just frozen. I don't know much about my setup, but I think it's a pretty standard Henkaku Ensō setup on 3.60. I installed the vpk by transferring it over via the molecularShell ftp server and running it.

**Comment by devnoname120** [comment]
Seems fine here, are you sure that your wifi works?
You can also try to delete the `ux0:/data/VitaHbBrowser` folder.

**Comment by Felthry** [comment]
Well, what do you know, I tried opening it again and it worked perfectly. I didn't even change anything.

**Comment by devnoname120** [comment]
Weird, I'd guess bad network or server temporarily down.

**Comment by simplyargyll** [comment]
Having this issue on 3.68
