### ISSUE TITLE
Downloads fail with “Network: Cannot send request” if server uses TLS 1.2

### ISSUE THREAD

**Issue by rsn8887** [devnoname120/vhbb#39]
Vita HBB now fails do download anything from bintray (almost any file hosted on VitaDB) with the error message “network: cannot send request”, on 3.60. The Retroarch nightly download is on a different server and works fine, but only if I set the url to http. Using https doesn’t work there either

I think since July 24, bintray forces everything to https with TLS 1.2 protocol, and stopped support for older TLS. It seems like TLS 1.2 is not supported by Vita HBB at least on the 3.60 kernel.

**Comment by devnoname120** [comment]
Indeed, I will switch to a library that uses curl under-the-hood because TLS 1.2 is not supported by `sceHttp` (at least on 3.60).
I plan to either use [cURLpp](https://github.com/jpbarrette/curlpp) or [cpr](https://github.com/whoshuu/cpr).

**Comment by rsn8887** [comment]
I confirm that it is not limited to 3.60. Even on 3.68, I get the same error “Network: Cannot send request” when using https.

**Comment by devnoname120** [comment]
@rsn8887 What if you access https://bintray.com/ from the web browser on 3.68?

**Comment by rsn8887** [comment]
On 3.68:
- The webpage https://bintray.com displays correctly.

- Using the built-in web browser, downloads from VitaDB also work. I just had to install download_enabler.suprx to enable downloading of arbitrary filetypes. I can go to vitadb.rinnegatamante.it in the browser and click on the download link for any homebrew, and it downloads just fine. The files appear under `ux0:download` and are ok.


On 3.60:
- Using the built-in web browser, trying to access https://bintray.com or trying to start downloads from vitadb.rinnegatamante.it just give a system error, as expected: `Could not communicate using SSL (C2-14900-4)`

-

**Comment by FrickinJon** [comment]
On 3.65:

Same behavior as 3.60. If i atttempt to navigate to [](https://bintray.com) I get the C2-14900-4 (could not communicate using SSL) error.

**Comment by devingDev** [comment]
Does the  libcurl in vita support TLS 1.2?

**Comment by devingDev** [comment]
If this was open source we could help much easier 🤔

**Comment by joel16** [comment]
Hey devnoname120 (Sensei) 
The problem with libcurl is that its pretty slow. I remember using it with the 3DS after the introduction of TLS 1.2 for GitHub. Is curl the only way around this?

**Comment by devingDev** [comment]
3ds != vita 🤔

**Comment by devnoname120** [comment]
@joel16 Might it not be just the 3DS port that's slow?

**Comment by devingDev** [comment]
I just remembered VitaCord is using libcurl 🤣 

Here code which is used for downloading images from discord .

https://github.com/devingDev/VitaCord/blob/master/src/VitaNet.cpp#L302

**Comment by joel16** [comment]
@devnoname120, could be I don't really know. Give it a shot and let me know how it goes. I thought 3.68 fixed TLS 1.2 though so I'm kind of confused here.

**Comment by devingDev** [comment]
Visiting github.com on my 3.68 hencore works whereas the 3.60 immediately fails with some SSL error (C2-14900-4)

**Comment by devnoname120** [comment]
@joel16 3.68 adds TLS 1.2 support but many users will stay on 3.65 for Ensō, so I need to switch to cURL. Anyway, I already planned to switch to cURLpp / cpr because it will improve code readability and maintainability.
