### ISSUE TITLE
Support for 3.65-3.68

### ISSUE THREAD

**Issue by simplyargyll** [devnoname120/vhbb#40]
On 3.68 the application hangs and eventually crashes the console

**Comment by rsn8887** [comment]
Strange, I can start it just fine using 3.68 h-encore. 

But the only download that works at the moment is Retroarch, presumably because it is the only HB on VitaDB/VitaHBB that is not hosted on bintray via SSL.

**Comment by ivan2340** [comment]
First boot takes quite a while, are you sure it actually hangs? I have it running on 3.67 h-encore although it does crash occasionally

**Comment by nchowning** [comment]
I'm having a similar issue. On 3.68 the app loads but anytime I select an app within vhbbb & press x to load information about it, it hangs for a few seconds and then pops up "An error has occurred in the following application (C2-12828-1)"

**Comment by devingDev** [comment]
#42 should fix most or all issues ( except the long first load)

**Comment by devnoname120** [comment]
Can you try https://github.com/devnoname120/vhbb/releases/tag/0.82?

**Comment by mileyrock** [comment]
still doesnt work it crashes

**Comment by Scrxtchy** [comment]
![](https://img.shields.io/badge/works-on%20my%20machine-green.svg)

**Comment by nchowning** [comment]
I'll give this a try later today

**Comment by devnoname120** [comment]
@mileyrock @nchowning Can you try again and report back? Please take a video if it crashes, thanks.

**Comment by Sammyhusky** [comment]
3.68 vhbb .82 loads appropriately but will not start any downloads, says "network: cannot Send Request"

**Comment by drewmullen** [comment]
*.82 is crashing for me too. app loads, slow fade from white screen (says gekihen homebrew contest) then the app crashes and produces a log file that looks ecrypted (or i dont have extension to read).

error: "an error has occured in the following application (C2-1282801)

using 3.68

**Comment by devnoname120** [comment]
Unfortunately I only have a vita running `3.60` so it's hard for me to provide you with assistance.

**Comment by devnoname120** [comment]
Could someone try with [version 0.83](https://github.com/devnoname120/vhbb/releases/tag/0.83) and give me the logs?

**Comment by TheoCaroff** [comment]
Hi, I try with the 0.83 version on Vita 3.65 HENkaku and I have this message : 
Error (C2-12828-1)
Save Core File Succeeded.
Ux0:data/psp2core-....-eboot.bin.pspdmb

Need you something else ?

**Comment by TheoCaroff** [comment]
After reinstallation in safe mode with Vita Shell and lanch in unsafe mode it's work.
I don't understand why when I install in unsafe mode it doesn't work.
Sorry I haven't note the full error message.
The LOG : [VHBB_2018-12-29_23-23-23.log](https://github.com/devnoname120/vhbb/files/2717321/VHBB_2018-12-29_23-23-23.log)

**Comment by EmuAGR** [comment]
Delete the manual DNS server from WiFi network settings. Turn it to automatic since the server is down.

**Comment by devnoname120** [comment]
@nchowning @null1024 @simplyargyll @mileyrock Did you try to disable any DNS settings on your vita like @EmuAGR suggested?

**Comment by devnoname120** [comment]
Nobody answered and it seems to work for some 3.65/3.68 users. The issue is most likely something else (bad DNS, etc.) and they *just* happen to be on these firmware.
