### ISSUE TITLE
network error!

### ISSUE THREAD

**Issue by j0s3ph19** [devnoname120/vhbb#44]
i have "network error" on all (or maybe 95% of all stuff) 
i tryed for 2-3 week but i still have this problem
tested on 3.60 henkaku r11 and on 3.67 h-encore psvita

i think is a HTTPS (ssl) problem 
indeed some download work, because is from another server with old ssl or with HTTP and not HTTPS

the HTTPS problem also appeared on pkgj, solved simply modifying https to http on the server link list file

**Comment by devnoname120** [comment]
Have you tried with the latest version?
https://github.com/devnoname120/vhbb/releases/latest

**Comment by j0s3ph19** [comment]
yeah yeah, latest version work fine :D thanks!

**Comment by j0s3ph19** [comment]
yeah yeah, latest version work fine :D thanks!

**Comment by devnoname120** [comment]
You're welcome!
