### ISSUE TITLE
Freeze after installing package

### ISSUE THREAD

**Issue by ok2094** [devnoname120/vhbb#45]
Phat Vita Enso 3.65 VHBB 0.82
The store browser works fine, except that it froze after downloading and installing Custom Themes Manager. I couldn't quit the app nor did any of the face buttons do anything. I could press the power button and the screen would go black, but pressing it again would just turn it back on without the lockscreen. Had to force reboot my vita. The installation of the Custom Themes Manager was fine.

**Comment by devnoname120** [comment]
I cannot reproduce your issue, maybe there are memory leaks somewhere.
