### ISSUE TITLE
Aggregate autoplugin

### ISSUE THREAD

**Issue by eze92** [devnoname120/vhbb#48]
Hi can they aggregate the autoplugin vpk for download since app ?

**Comment by devnoname120** [comment]
Please ask @rinnegatamante.

**Comment by Rinnegatamante** [comment]
Whenever it will be rewrote not using an interpreter that breaks GPL license, fine. (Eg. rewrote using lpp-vita or C/C++).

**Comment by eze92** [comment]
oh I understand, Its a pity that His language that use its not compatible, thanks for response
