### ISSUE TITLE
Respect the X/O cancel/confirm button setting

### ISSUE THREAD

**Issue by assholehoff** [devnoname120/vhbb#54]
Currently X always confirm and O always cancel, even though I set O to confirm (Japanese & Nintendo style) in the HENkaku Settings. Would be nice if the Browser either respects this or gets its own option to swap.

**Comment by devnoname120** [comment]
This is a good suggestion!

**Comment by robsdedude** [comment]
e.g. https://github.com/d3m3vilurr/vita-savemgr/blob/b5b5c24737da34a28646821fe0429be9f045d4f9/src/input.c#L11
