### ISSUE TITLE
random crashes when scrolling/overloading

### ISSUE THREAD

**Issue by kattstof** [devnoname120/vhbb#57]
on 3.60 enso anytime you fast scroll/ press X to view more description it'll crash randomly
I've experienced it during a download when scrolling. it's a gpu crash , however it's the only vita app that causes it so it isn't faulty hw

**Comment by praefectum** [comment]
It happens the same on my PCH2004 running 3.60 with enso.
Black screen of death or just stuck on VHBB main screen, hard reset needed then.

**Comment by lanner** [comment]
or just delete the folder  ux0:/data/VitaHbBrowser, sometimes it's just the download have a probeme at the first start

**Comment by praefectum** [comment]
> or just delete the folder ux0:/data/VitaHbBrowser, sometimes it's just the download have a probeme at the first start

Seems to be working, thank you!

**Comment by kattstof** [comment]
seems to fix it here as well, cheers!
