### ISSUE TITLE
Description Box Scrolling

### ISSUE THREAD

**Issue by MonfGeiger** [devnoname120/vhbb#59]
When we boot up the homebrew browser in the ps vita and we open up any homebrew link, we get a picture in the middle right, a download button in thew middle/top left, and a description box below, but the text always looks so squished together and never shows all of it, like if there's a list of features, credits to contributors/other devs, etc...

My request is to get a word wrap function properly applied to the vita homebrew browser app, and maybe add in a scroll function to the description box, either by using the right analog stick, or the touch screen method of movement

If possible, one other feature request that just popped into my head, is a search bar function on the app, so we aren't limited to going to the emulators section or the ports section and have to manually look for the app we want

**Comment by devnoname120** [comment]
@robsdedude has added a search bar, this should come in the next version of VHBB.
About the description this would be a great addition!
