### ISSUE TITLE
Can't Access Site Or Homebrews

### ISSUE THREAD

**Issue by rock6663** [devnoname120/vhbb#62]
**Describe the bug**
im on 3.65 enso im using itsl and its working correctly but when i use vhbb i get network cant send request after 2 retrys i cant download anything after a moment i realised i cant access to https://vitadb.rinnegatamante.it/ too now ı cant enter app either

**Screenshots**
![untitled](https://user-images.githubusercontent.com/48176390/53694282-ac47a300-3dbd-11e9-9738-4caa6e2bd405.png)

**Log file**

[VHBB_2019-03-03_14-04-54.log](https://github.com/devnoname120/vhbb/files/2923023/VHBB_2019-03-03_14-04-54.log)

**Comment by rock6663** [comment]
Ok Problem İs Not On Me

**Comment by devnoname120** [comment]
VitaDB was down, it should work again now.
