### ISSUE TITLE
Clean up includes

### ISSUE THREAD

**Issue by robsdedude** [devnoname120/vhbb#64]
Especially the `global_include.h` should be removed and all units should just include what they need.

One idea is to do a text replace (replace `include "global_include.h"` with it's content) and use some include optimizer to get rid of unused includes afterwards. Should be easy enough that way.

**Comment by devnoname120** [comment]
Closed by https://github.com/devnoname120/vhbb/commit/3fb730072f96449490ba52f2e22bc2da2d1b378d.
