### ISSUE TITLE
Touch back buttons

### ISSUE THREAD

**Issue by St0ner1995** [devnoname120/vhbb#67]
When looking at details for apps, there is no touch back button. while not necessary, this would be a nice feature and match the design of other vita apps like the PSN Store and Settings apps

**Comment by devnoname120** [comment]
https://github.com/devnoname120/vhbb/blob/archive/old-master/assets/img_preview_btn_back.png
https://github.com/devnoname120/vhbb/blob/archive/old-master/assets/img_preview_btn_back_pressed.png

**Comment by devnoname120** [comment]
Can find development version where this is fixed in the artifacts of the build: https://dev.azure.com/devnoname120/devnoname120/_build/results?buildId=32
