### ISSUE TITLE
It crashes before starting

### ISSUE THREAD

**Issue by HuascarOk** [devnoname120/vhbb#76]
The app used to work fine, but now it just doesnt... Now when i try to launch the app, it just crashes.

1. Just start the app.
2. Wait for the app.
3. See the error C2-12828-1

It is supposed to boot and send me to the main menu, where i'm supposed to see games, emulators, ports and tools, but it doesn't even get's trouhgt the loading screen.

![2019-10-14-023110](https://user-images.githubusercontent.com/43837752/66732832-6fe82500-ee2b-11e9-80f1-26486177bb4c.jpg)
![2019-10-14-023112](https://user-images.githubusercontent.com/43837752/66732833-6fe82500-ee2b-11e9-9262-b04b40d37b3a.jpg)

_**### LOG FILE:**_
VHBB started.
- Version: 00.91
- Commit: ca81c8c495ede05c2f64af9fdd8d1434d9ba49bb
- GitHub: https://github.com/devnoname120/vhbb/tree/ca81c8c495ede05c2f64af9fdd8d1434d9ba49bb
- OS: 3.72

[/home/devnoname120/psv/vhbb/src/vitaPackage.cpp:199 VitaPackage::VitaPackage()]  Loading PAF
[/home/devnoname120/psv/vhbb/src/vitaPackage.cpp:213 VitaPackage::~VitaPackage()]  Unloading PAF
[/home/devnoname120/psv/vhbb/src/network.cpp:208 Network::TestConnection()]  Content length: 8
[/home/devnoname120/psv/vhbb/src/update.cpp:91 Update::getVersionInfo()]  sceIoRemove(ux0:/data/VitaHbBrowser/latest_version.yml) = 0x80010002
[/home/devnoname120/psv/vhbb/src/network.cpp:109 Network::Download()]  Downloading https://vhbb.download/version.php to ux0:/data/VitaHbBrowser/latest_version.yml
[/home/devnoname120/psv/vhbb/src/network.cpp:162 Network::Download()]  Done downloading https://vhbb.download/version.php
[/home/devnoname120/psv/vhbb/src/update.cpp:77 readVersionYAML()]  Version field successfully parsed 0 91
[/home/devnoname120/psv/vhbb/src/update.cpp:112 Update::getVersionInfo()]  Latest online version: 00.91
[/home/devnoname120/psv/vhbb/src/update.cpp:129 Update::getVersionInfo()]  Current version 00.91 is up-to-date
[/home/devnoname120/psv/vhbb/src/network.cpp:109 Network::Download()]  Downloading https://rinnegatamante.it/vitadb/list_hbs_yaml.php to ux0:/data/VitaHbBrowser/homebrews.yaml
[/home/devnoname120/psv/vhbb/src/network.cpp:156 Network::Download()]  cURLpp exception:  https://rinnegatamante.it/vitadb/list_hbs_yaml.php 
[/home/devnoname120/psv/vhbb/src/fetch_load_icons_thread.cpp:30 FetchLoadIcons()]  Couldn't load database: NetworkError: 
[/home/devnoname120/psv/vhbb/src/vitasdk_quirks.cpp:39 terminate_logger()]  terminate() because of NetworkError:

**Comment by HuascarOk** [comment]
In my opinion, the problem comes from the web page where it gets the apps. I tried entering before this started happening and it was alright, but now it doesn't even loads.
https://vitadb.rinnegatamante.it/#/

**Comment by HuascarOk** [comment]
Meanwhyle, i know 2 pages from wich we can get apps from:
1: https://store.brewology.com/vita/homebrew.php?lang=
2: https://wololo.net/downloads/index.php/platform/3

**Comment by devnoname120** [comment]
@HuascarOk Could you try again? The page seems up again (even though it's slow).

**Comment by HuascarOk** [comment]
@devnoname120 I've tried again and I still get the same error, and I tried entering the page even on my computer and it doesn't go up 7w7

**Comment by HuascarOk** [comment]
And btw i have to say that i really love your work for the ps vita community, you're awesome 💪🏻

**Comment by HuascarOk** [comment]
@devnoname120 Thank you, the page is up and running again, same for the app, you're the best :3 and i was wondering how could i learn myself how to make plugins and homebrew for the vita?

**Comment by devnoname120** [comment]
@HuascarOk If you're not familiar with C or C++ I suggest you to try [Lua Player Plus](https://github.com/Rinnegatamante/lpp-vita), it's one of the easiest way to create apps for the Vita.

You can find some examples here: https://github.com/Rinnegatamante/lpp-vita
If you need help, I think that people from this Discord server can help you out: https://discord.gg/PyCaBx9

**Comment by HuascarOk** [comment]
Thank you, for this advice and for everything :3 I hope you continue making all those innovations that we love so much, you're amazing and again, thank you.
