### ISSUE TITLE
Crashes when downloading ScummVM Nightly

### ISSUE THREAD

**Issue by rsn8887** [devnoname120/vhbb#77]
**Describe the bug**

Crashes when downloading ScummVM nightly or Retroarch nightly 

Note: ScummVM nightly and Retroarch nightly are hosted on a different server than other vitadb, See download link on VitaDB. Download works using other methods.

**To Reproduce**

Go to ScummVM Nightly, click download

**Expected behavior**

Should download ScummVM nightly

**Screenshots**

**Log file**

**Comment by devnoname120** [comment]
Are you able to download other homebrews?
If not, this is a duplicate of https://github.com/devnoname120/vhbb/issues/75.

**Comment by rsn8887** [comment]
I thought I did, but apparently not. I just tried to download a random homebrew and also got the crash. :/
