### ISSUE TITLE
C2-12828-1 Crash when selecting any homebrew

### ISSUE THREAD

**Issue by PipeWarp** [devnoname120/vhbb#80]
**Describe the bug**
Crashes when i select any homebrew
Im using a psvita slim with enso 3.65

**To Reproduce**

Open VHBB, select any homebrew and it crashes

**Log file**
[VHBB_2020-04-05_19-57-03.log](https://github.com/devnoname120/vhbb/files/4434563/VHBB_2020-04-05_19-57-03.log)

-->

**Comment by fexofenadine** [comment]
this was reported October 12 2019 in [issue 75](https://github.com/devnoname120/vhbb/issues/75) 

theres a pull request that fixes the issue, just be patient and @devnoname will merge the request and release a new build

**Comment by tekktonic** [comment]
@fexofenadine I believe this is a distinct bug. I've built VHBB with the branch you're talking about and it still crashes whenever I try to select an app. I can't even get to the point where I choose to download.

**Comment by robsdedude** [comment]
@tekktonic the fix for #75 is now deployed. VHBB will ask you to update. Do so and please confirm if the issue still exists (I can't reproduce it right now), else close the issue.

**Comment by PipeWarp** [comment]
kk, thanks

**Comment by tekktonic** [comment]
@robsdedude Latest build appears to fix it for me. Successfully installed a package from the homebrew store.

No clue why it didn't work for me when I built the branch that the PR came from.

**Comment by robsdedude** [comment]
Is it also working for you, @PipeWarp?

> @robsdedude Latest build appears to fix it for me. Successfully installed a package from the homebrew store.
> 
> No clue why it didn't work for me when I built the branch that the PR came from.

Maybe there was a problem with your build environment. E.g. outdated Vita SDK or some misconfiguration, who knows.

**Comment by PipeWarp** [comment]
> Is it also working for you, @PipeWarp?
> 
> > @robsdedude Latest build appears to fix it for me. Successfully installed a package from the homebrew store.
> > No clue why it didn't work for me when I built the branch that the PR came from.
> 
> Maybe there was a problem with your build environment. E.g. outdated Vita SDK or some misconfiguration, who knows.

Yep it works, forgot to close it my bad
