### ISSUE TITLE
Crash at Startup (1st open)

### ISSUE THREAD

**Issue by joshworx** [devnoname120/vhbb#82]
Don't have a tai folder, deleted VHBBrowser folder, tried uninstalling reinstalling, nothing worked, still a crash after the GEKIHEN screen after first open.  After closing and reopening, seems to work.

When trying to download, it hangs, retries, and gives a 404 not found error.

**Comment by devnoname120** [comment]
I know VitaDB has been experiencing denial-of-service attacks recently. Could you try again?

**Comment by solemgar** [comment]
Same issue here. Brand new install of 0.92. Getting error C2-12828-1 after GEKIHEN screen. Deleted the relevant folder under ux0:/data. Doesn't boot at all :(

**Comment by bonkers1234** [comment]
Same here. CFW 3.60. Got error C2-12828-1 after the GEHIKEN screen. Doesn't matter if i close it and open it again. version 0.92 and also tried deleting the folder under ux0:/data

**Comment by devnoname120** [comment]
VitaDB is down again.

**Comment by bonkers1234** [comment]
Yes, just saw : https://vitadb.rinnegatamante.it/ doesn't work. Apologies for the false positive! I'll wait until vitadb is up again and retry.

**Comment by robsdedude** [comment]
Maybe VHBB should handle network errors more gracefully, in general… Nice error message instead of just crashing would be a good start, probably.

**Comment by devnoname120** [comment]
Yes I agree it would be nice to handle network errors.

**Comment by mightysashiman** [comment]
Have the same issue on first launch. After the GEKIHEN screen, it goes to black screen, nothing happens for an infinite amount of time. Then at some point error C2-12828-1 occurs. vitadb is accessible ; I just used it to download VHBB !
