### ISSUE TITLE
Error c2-12828-1 Even on the newest version

### ISSUE THREAD

**Issue by MasaoAniko** [devnoname120/vhbb#85]
So i have looked at multiple places, looked at videos, but i cannot for the life of me, find a solution. I recently got a PSVita, downloaded the browser, but whatever i try, it does not want to work. 

I keep getting the Error c2-12828-1

I attached the log with it, i hope you guys can help me, cause i have been trying for a couple of days now.
[VHBB_2020-06-14_10-07-21.log](https://github.com/devnoname120/vhbb/files/4776061/VHBB_2020-06-14_10-07-21.log)

**Comment by Pachol5501** [comment]
I have the same problem with the newest version. It happened after I installed EasyVPK. Now I cannot run these apps

**Comment by StarWolf3000** [comment]
Did you have a peek on the log?
`cURLpp exception: The requested URL returned error: 503 Service Temporarily Unavailable https://rinnegatamante.it/vitadb/list_hbs_yaml.php`
`Couldn't load database: NetworkError: The requested URL returned error: 503 Service Temporarily Unavailable`

**Comment by Pachol5501** [comment]
So I just have to wait until the website would be fixed?

**Comment by StarWolf3000** [comment]
Yeah, but you can check it again, at least for me this url doesn't throw any errors right now (in browser on Desktop, not on Vita). Also keep in mind, that the website is secured by Cloudflare, so that may be an important factor.

**Comment by MasaoAniko** [comment]
This happens on both EasyVPK with me and the Homebrew Store
