### ISSUE TITLE
C2-12828-1

### ISSUE THREAD

**Issue by d4rkleaderz** [devnoname120/vhbb#88]
Are you sure that you are running the latest version of VHBB? 
yes

**Describe the bug**
I search APP or click download and i get this error C2-12828-1 and VHBB crash and return to live area (home)

**To Reproduce**
1. Go to 'Search OR Download Buton'
2. See error

**Expected behavior**
I search APP or click download and i get this error C2-12828-1

**Log file**
[VHBB_2020-09-10_11-45-11.log](https://github.com/devnoname120/vhbb/files/5203039/VHBB_2020-09-10_11-45-11.log)

**Comment by RinMaru** [comment]
if your not going to add description then dont bother posting

**Comment by d4rkleaderz** [comment]
This is fixed.. sorry.. comment bug with edge insider loll

**Comment by RinMaru** [comment]
lol alright

**Comment by Masamune3210** [comment]
I don't see anything wrong in the log, and 12828-1 is general error, so I don't know if you are going to get much help unfortunately. This has been a issue for a while, but make sure you are on the latest version
