### ISSUE TITLE
installing retroarch

### ISSUE THREAD

**Issue by toomanylegos** [devnoname120/vhbb#9]
whenever I try to install retroarch with this app it spends 2-3 minutes on the download stage and than displays ''cannot open zip file''. Also I am wondering where this app downloads the vpks to.

**Comment by ArkSource** [comment]
Thanks for advising on this issue.
the vpk is downloaded to ux0:temp/ and removed after installation (or if installation fails).

**Comment by devnoname120** [comment]
@toomanylegos 

I can't reproduce your issue, RetroArch installs fine here.

1) Make sure that you're using the version 0.8
2) Do you have enough memory available on your memory card? Make sure that you have more than 500 MB free on `ux0:` before installing it.

**Comment by toomanylegos** [comment]
I am running v0.8 and I know I should have more than enough space on my memory card (it's a 16GB card and I have about 1GB of stuff on it) and if it helps, Vitashell and Molecular shell both failed at installing it too. I don't know if I need extra files to install RetroArch but I think if it did they would be included in the package. Also I'll include a video link.
https://www.youtube.com/watch?v=5IOJRDvz8Gk
(sorry about the delay, I got caught up on a virus :( . But, its all fixed now)

**Comment by devnoname120** [comment]
I think that the download failed. Could you try on a faster and more stable wifi network?

**Comment by toomanylegos** [comment]
thanks! worked perfectly first try after moving to the room my router was in lol. Thank you for helping!

**Comment by devnoname120** [comment]
You're welcome.

**Comment by devnoname120** [comment]
@toomanylegos Are you able to reproduce this issue in the latest version? I switched to cURL so the behavior should be different.
