### ISSUE TITLE
ISP (e.g. Xfinity) is blocking some requests

### ISSUE THREAD

**Issue by JimmyGrinch** [devnoname120/vhbb#94]
Whenever I launch Vita Homebrew Browser I get the c2-12828-1 error (running .92). I saw some people got the error when they were downloading applications off the browser, but I didn't find any solutions for the error on launching vhbb. Anyone know a solution? (restart/reinstall/rebuilding database already tried)

log (I think this is the right one):
[VHBB_2020-11-16_17-57-57.log](https://github.com/devnoname120/vhbb/files/5550807/VHBB_2020-11-16_17-57-57.log)

![IMG-1212](https://user-images.githubusercontent.com/74577141/99334915-c34e5300-2835-11eb-8c1f-8dc646d05508.jpg)

**Comment by devnoname120** [comment]
@JimmyGrinch Could you try again today? VitaDB might have been done. In the next version of VHBB there will be a better dialog.

**Comment by JimmyGrinch** [comment]
deleted vhbb, reinstalled .92. I still get the same error. When I click the "click here for debug logs" I also get the error, but the log still appears in ux0:log/

**Comment by JimmyGrinch** [comment]
I dont know if it helps or not but I also get the same error with easyvpk

**Comment by JimmyGrinch** [comment]
Figured it out! It turns out my service provider was blocking vitadb, and the vita couldn't load up the popup block page. It works on other networks now after a format.

**Comment by MasonBergstrom** [comment]
> Figured it out! It turns out my service provider was blocking vitadb, and the vita couldn't load up the popup block page. It works on other networks now after a format.

That's 100% it. Been fighting this forever. Xfinity was blocking it, tethering from my phone let me in just fine.
